### ISSUE TITLE
maybe reasonable: swap col 1 and 2 in output

### ISSUE THREAD

**Issue by martin-raden** [fabriziocosta/RaSE#12]
that way we get directly the mutation encoding in column style, which eases copy and paste!?

just a suggestion that we can also drop.. but for bioinformaticians it doesnt make a difference and for all others it might be useful?!

**Comment by fabriziocosta** [comment]
Or perhaps would it be better to add the mutation string as second line in the output?

**Comment by martin-raden** [comment]
no.. it is about "preNt_Pos_mutNt" encoding of mutations.. right now, the columns are in "pos preNt mutNt" order... 

but as I said, just a suggestion

**Comment by mmiladi** [comment]
"Wild index mut" order sounds a good idea!
