### ISSUE TITLE
Graph Context length option

### ISSUE THREAD

**Issue by mmiladi** [fabriziocosta/RaSE#22]
To get a (super) local comparison score between wild and mutant feature graphs: An option to compare and calculate RaSE score on a sub-graph surrounding the SNP location. This option can be implemented to set vector weight(?) of distant locations to zero.

**Comment by mmiladi** [comment]
Hi @fabriziocosta, Today @martin-mann and I were discussing about the benchmark. The conclusion was without having this locality feature, it would not be a fair comparison of the tools.

**Comment by fabriziocosta** [comment]
Ok guys, I'll work on it.

**Comment by fabriziocosta** [comment]
ok, done. the readme still needs to be updated. 
Note that EDeN has to be updated.

check the notebook for usage.
now there is a new parameter: importance_semi_window
e.g. 
  print rase.stability_score(0,'A', importance_semi_window=5)

**Comment by mmiladi** [comment]
Wonderful @fabriziocosta ! Is it a rectangular weight function with a single width option, or a trapezoid one with two window width options?

**Comment by fabriziocosta** [comment]
in all cases the weights are given as a single rectangular window, inside the window the weight is 1, outside is 0
there are two ways to specify the window:
1. rase.stability_score(0,'A', importance_semi_window=5) 
in this way one gives the position, the nt and the semi window around that position to compute the stability score
2. rase = StructuralStabilityEstimator(seq, k=6, avg_bp_prob_cutoff=0.1, importance_window_begin=2, importance_window_end=12)
rase.compute_stability_scores()
in this way one gives explicitly the begin and end positions for the window, the stability score is then still computed for all positions
